# Replace this with the Project Key shown in your SonarQube/SonarQube Cloud project.
sonar.projectKey=rmenaka0710

# For SonarQube Cloud, uncomment and replace with your organization key.
# sonar.organization=YOUR_ORGANIZATION_KEY

sonar.sources=.
sonar.exclusions=node_modules/**,.github/**
sonar.sourceEncoding=UTF-8
