name: SonarQube CI/CD Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # For self-hosted SonarQube Server, also create SONAR_HOST_URL in GitHub Secrets.
          # For SonarQube Cloud, remove the next line if your setup does not require it.
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v8
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          

  deploy:
    needs: sonar
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Demo deployment
        run: |
          echo "Quality Gate passed"
          echo "Deploying application..."
          echo "Deployment successful!"
